---
apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-kafka-mirror
  labels:
    app: strimzi
    mcp: strimzi
    system: strimzi
---
apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-mirror-maker
  labels:
    app: strimzi
    mcp: strimzi
    system: strimzi
