---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: secondary-combined
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: mcp-cluster-secondary
    mcp: strimzi
    system: strimzi
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: mcp-cluster-secondary
  namespace: strimzi-kafka
  labels:
    mcp: strimzi
    system: strimzi
spec:
  kafka:
    version: 4.2.0
    metadataVersion: 4.2-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
