---
apiVersion: kafka.strimzi.io/v1
kind: KafkaMirrorMaker2
metadata:
  name: mcp-mirror-maker
  namespace: strimzi-mirror-maker
  labels:
    mcp: strimzi
    system: strimzi
spec:
  version: 4.2.0
  replicas: 1
  target:
    alias: mcp-cluster-mirror
    bootstrapServers: mcp-cluster-mirror-kafka-bootstrap.strimzi-kafka-mirror.svc:9092
    groupId: mcp-mirror-maker
    configStorageTopic: mirrormaker2-cluster-configs
    statusStorageTopic: mirrormaker2-cluster-status
    offsetStorageTopic: mirrormaker2-cluster-offsets
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
    - source:
        alias: mcp-cluster
        bootstrapServers: mcp-cluster-kafka-bootstrap.strimzi-kafka.svc:9777
        tls:
          trustedCertificates:
            - secretName: mcp-cluster-cluster-ca-cert
              pattern: "*.crt"
        authentication:
          type: scram-sha-512
          username: mm2-user
          passwordSecret:
            secretName: mm2-user
            password: password
      sourceConnector:
        tasksMax: 1
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
      checkpointConnector:
        tasksMax: 1
        config:
          checkpoints.topic.replication.factor: 1
          sync.group.offsets.enabled: true
      topicsPattern: ".*"
      topicsExcludePattern: "__.*"
      groupsPattern: ".*"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
