---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-consumer
  namespace: strimzi-kafka-mirror
  labels:
    app: mirror-consumer
    mcp: strimzi
    system: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-consumer
  template:
    metadata:
      labels:
        app: mirror-consumer
    spec:
      containers:
        - name: mirror-consumer
          image: quay.io/strimzi-test-clients/test-clients:latest-kafka-4.2.0
          env:
            - name: CLIENT_TYPE
              value: KafkaConsumer
            - name: BOOTSTRAP_SERVERS
              value: mcp-cluster-mirror-kafka-bootstrap:9092
            - name: TOPIC
              value: mcp-cluster.mcp-test-topic
            - name: GROUP_ID
              value: mirror-verify-group
            - name: MESSAGE_COUNT
              value: "999999999"
