apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-mcp-metrics
  labels:
    mcp: strimzi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: strimzi-mcp
  podMetricsEndpoints:
    - path: /q/metrics
      port: http
