apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamshub-strimzi-mcp
spec:
  template:
    spec:
      containers:
        - name: strimzi-mcp
          imagePullPolicy: Always
          env:
            - name: QUARKUS_LOG_CATEGORY__IO_STREAMSHUB_MCP__LEVEL
              value: "DEBUG"
