apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator/000-Namespace.yaml
  - operator/010-ServiceAccount.yaml
  - operator/020-ClusterRole.yaml
  - operator/030-ClusterRoleBinding.yaml
  - operator/040-Crd-kafkaaccess.yaml
  - operator/050-Deployment.yaml
  - resources/010-Kafka-MCP-access.yaml
