apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
---
# OperatorGroup for openshift-operators-redhat (required if not already present)
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
spec: {}
