---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-cloud-eck
  namespace: openshift-operators
spec:
  channel: stable
  name: elastic-cloud-eck
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
