apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamshub-mcp

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: strimzi-mcp
- includeTemplates: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: streamshub

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml

images:
- name: quay.io/streamshub/strimzi-mcp
  newTag: latest
