apiVersion: v1
kind: Service
metadata:
  name: streamshub-strimzi-mcp
spec:
  selector:
    app.kubernetes.io/name: strimzi-mcp
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
