apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kafka-connect
patches:
  - target:
      group: kafka.strimzi.io
      version: v1
      kind: KafkaConnect
      name: mcp-connect
    path: patch-build-output.yaml
