---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-consumer
  namespace: strimzi-kafka
  labels:
    app: http-consumer
    mcp: strimzi
    system: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-consumer
  template:
    metadata:
      labels:
        app: http-consumer
    spec:
      containers:
        - name: http-consumer
          image: quay.io/strimzi-test-clients/test-clients:latest-kafka-4.2.0
          env:
            - name: CLIENT_TYPE
              value: HttpConsumer
            - name: HOSTNAME
              value: mcp-bridge-bridge-service
            - name: PORT
              value: "8080"
            - name: TOPIC
              value: mcp-bridge-topic
            - name: GROUP_ID
              value: mcp-bridge-http-group
            - name: MESSAGE_COUNT
              value: "999999999"
            - name: POLL_INTERVAL
              value: "5000"
            - name: MESSAGE_TYPE
              value: json
